#+TITLE: COPYING

* Main program and license

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public
License along with this program, in the file =licenses/AGPLv3.txt=.
If not, see [[http://www.gnu.org/licenses/]].


* Documentation

Documentation files located in the =docs/= directory tree and all
original documentation theme CSS and assets (including image files)
are free software and free documentation: you can redistribute it
and/or modify it under the terms of the GNU Affero General Public
License as published by the Free Software Foundation, either version 3
of the License, or (at your option) any later version.  Additionally,
these files are also available, at your option, under
[[http://creativecommons.org/licenses/by-sa/4.0/][Creative Commons Attribution-Sharealike 4.0 International]].

You should have received a copy of the GNU Affero General Public
License along with this program, in the file =licenses/AGPLv3.txt=.
If not, see [[http://www.gnu.org/licenses/]].

You should have received a copy of the Creative Commons
Attribution-Sharealike 4.0 International license along with this
program, in the file =licenses/cc-by-sa-4.0.txt=.  If not, see
[[http://creativecommons.org/licenses/by-sa/4.0/legalcode.txt]].


* extlib / additional libraries

Additional library software has been made available in the =extlib/=
directory.  All of it is Free Software and can be distributed under
liberal terms, but those terms may differ in detail from the AGPL's
particulars.  See each package's license file in the extlib directory
for additional terms.
