#+TITLE: Swoptact: the FOSS contact management system

Swoptact: free software (AGPL licensed!) contact management for you
and your org!

Built by the fine folks at [[http://opentechstrategies.com/][Open Tech Strategies]].  Want to integrate
Swoptact into your org?  [[http://opentechstrategies.com/contact][OTS can help]]!

* Overview

** Abstract

We should have a high level overview of what Swoptact is and how it
could be useful to people here.

** User stories

These are stories about how various users make use of Swoptact

*** Why Sarah chose Swoptact

This is a high level overview of why Sarah thinks Swoptact will be
useful to her.

*** Sarah's big event

This user story talks about Sarah, the event she ran, and what
information she kept after the event.

**** Before the conference

Is there anything to do pre-conference?

**** Immediately after the conference

Does she record information here?

**** Later usage

** Interface
** Database

*** Users and permissions

Making use of Django's builtins

*** Contacts
*** Events


